import requests
import _thread
import time

accounts=[
'jumboargentinav008chivilcoy',
'jumboargentinav013santiagodelestero',
'jumboargentinav020lanus',
'jumboargentinav032buchardo',
'jumboargentinav036laplata2',
'jumboargentinav040salta',
'jumboargentinav051necochea',
'jumboargentinav052sanclemente',
'jumboargentinav056luroyguido',
'jumboargentinav064salta064',
'jumboargentinav070yerbabuena',
'jumboargentinav071terminal',
'jumboargentinav072americaybelgranotucuman',
'jumboargentinav073matedeluna',
'jumboargentinav110trescerritos',
'jumboargentinav113rioivshopping',
'jumboargentinav114juanbjusto',
'jumboargentinav122bahiablanca',
'jumboargentinav125sarmientotucuman',
'jumboargentinav127bahiablancaii',
'jumboargentinav134tucumanroca',
'jumboargentinav140oran',
'jumboargentinav150padua',
'jumboargentinav153moroni',
'jumboargentinav155castelarsur',
'jumboargentinav159merloii',
'jumboargentinav160morenoi',
'jumboargentinav162lujan',
'jumboargentinav164hurlingham164',
'jumboargentinav165mercedes165',
'jumboargentinav170sanmartinydemocracia',
'jumboargentinav171sarmientoyalen',
'jumboargentinav172godoycruzyavellaneda',
'jumboargentinav173manuelmolina',
'jumboargentinav175americatchuquisaca',
'jumboargentinav179sanmiguel',
'jumboargentinav180smartinysgodelest',
'jumboargentinav184lavalle',
'jumboargentinav185sanmartin1211',
'jumboargentinav187padrevazquez',
'jumboargentinav188pasodelosandes82',
'jumboargentinav189mendozaplazashopping',
'jumboargentinav191irigoyen858',
'jumboargentinav192rpanamericana',
'jumboargentinav19425demayoyjujuy',
'jumboargentinav195rioivbandanorte',
'jumboargentinav220lujan',
'jumboargentinav232villamariashopp',
'jumboargentinav234caseros',
'jumboargentinav241edison',
'jumboargentinav242patiopalmera',
'jumboargentinav243catamarca',
'jumboargentinav398rodeodelacruz',
'jumboargentinav399sanmartin',
'jumboargentinav402patricia',
'jumboargentinav413delaroza1986cdad',
'jumboargentinav415sarmientoyrivadavia',
'jumboargentinav417acha1360surcdad',
'jumboargentinav423villamercedes',
'jumboargentinav430funes',
'jumboargentinav432sanvicente',
'jumboargentinav433cipolletti',
'jumboargentinav434olmosi',
'jumboargentinav437ruta20',
'jumboargentinav440chacabuco',
'jumboargentinav453ruta9',
'jumboargentinav455zanni',
'jumboargentinav464sanfrancisco',
'jumboargentinav466armadaargentina',
'jumboargentinav472ipona',
'jumboargentinav475arguello475',
'jumboargentinav478bellville',
'jumboargentinav479rioivsabatini',
'jumboargentinav503marcosjuarez',
'jumboargentinav505sm505catamarcaiii',
'jumboargentinav544sanjuan544',
'jumboargentinav545tupungato',
'jumboargentinav546bdalvian',
'jumboargentinav548sancarlos',
'jumboargentinav550altosdelsolar',
'jumboargentinav631sanpedro',
'jumboargentinav633calle525entre8y9',
'jumboargentinav636calle13entre71y72',
'jumboargentinav638calle19entre530y531',
'jumboargentinav640calle47',
'jumboargentinav645ciudaddenieva',
'jumboargentinav646guemes',
'jumboargentinav647exodo',
'jumboargentinav655ciudadjudicial',
'jumboargentinav656saltasur',
'jumboargentinav657sarmientoyohiggins',
'jumboargentinav659cordobai',
'jumboargentinav660avalem',
'jumboargentinav669pergamino',
'jumboargentinav674resistencia',
'jumboargentinav677saladillo',
'jumboargentinav686gualeguaychu',
'jumboargentinav690riotercerocentro',
'jumboargentinav691pasodeloslibres',
'jumboargentinav692lanus692',
'jumboargentinav696sanjuan',
'jumboargentinav697pacheco',
'jumboargentinav698montegrande',
'jumboargentinav700cordoba700',
'jumboargentinav702lobos',
'jumboargentinav703canuelas',
'jumboargentinav704tresarroyos',
'jumboargentinav705larioja2',
'jumboargentinav706ptomadryn',
'jumboargentinav708larioja',
'jumboargentinav711tandil',
'jumboargentinav730labanda',
'jumboargentinav731ituzaingosalta',
'jumboargentinav752trelew',
'jumboargentinav767junin',
'jumboargentinav769rivadavia954',
'jumboargentinav803avdellibertadornorte',
'jumboargentinav853sanluisii',
'jumboargentinav854concordia',
'jumboargentinav855sextaseccion',
'jumboargentinav857labarraca',
'jumboargentinav859sanluisiii',
'jumboargentinav860sanluis',
'jumboargentinav887santiagodelesteroll',
'jumboargentinav902lainez',
'jumboargentinav903stopmonteros',
'jumboargentinav904stopconcepcion',
'jumboargentinav906stopalberdi',
'jumboargentinav910roca',
'jumboargentinav914malargue',
'jumboargentinav942hipermercado',
'jumboargentinav943parana',
'jumboargentinav944tapiales',
'jumboargentinav980parquesanmartinsalta',
'jumboargentinav983miramar',
]

def obtainTaxHubConfiguration(account):
  url = 'https://' + account + '.vtexcommercestable.com.br/api/checkout/pvt/configuration/orderForm'
  # print(url)
  accountTaxHubConfig = requests.get(url,
                                      headers={ 'VtexIdclientAutCookie': ''})
  json_response = accountTaxHubConfig.json()
  # print(json_response['taxConfiguration']['url'])
  print(json_response['taxConfiguration']['authorizationHeader'])
  print(json_response['taxConfiguration']['url'].split('an=')[1] == account)

num_threads = 0
for account in accounts:
  try:
      if num_threads % 50 == 0:
        time.sleep(2)
      _thread.start_new_thread( obtainTaxHubConfiguration, (account, ) )
      num_threads = num_threads + 1
  except:
      print('Error: unable to start thread')

time.sleep(60)
