export const getOrderForm= `query getOrderform($orderformId: ID){
    orderForm(orderFormId: $orderformId){
      clientProfileData{
        email
        firstName
        lastName
        document
        documentType
        phone
        corporateName
        tradeName
        corporateDocument
        stateInscription
        corporateDocument
        isCorporate
        profileCompleteOnLoading
        profileErrorOnLoading
        customerClass
        isValid
      }
      paymentData{
        installmentOptions{
          paymentSystem
          bin
          paymentName
          paymentGroupName
          value
          installments{
            count
            hasInterestRate
            interestRate
            value
            total
          }
          
        }
        paymentSystems{
          id
          name
          groupName
          validator{
            regex
            mask
            cardCodeRegex
            cardCodeMask
            weights
            useCvv
            useExpirationDate
            useCardHolderName
            useBillingAddress
          }
          stringId
          requiresDocument
          isCustom
          description
          requiresAuthentication
          dueDate
        }
        payments{
          paymentSystem
          bin
          accountId
          tokenId
          installments
          referenceValue
          value
        }
        availableAccounts{
          accountId
          paymentSystem
          paymentSystemName
          cardNumber
          bin
        }
        isValid
        }
      
      
    }
  }
  `